"""Self-check guardrails for answer quality verification.

Reuses the Pydantic self-healing validation pattern from
guardrail_self_correction_pydantic.py.
"""

import json
from typing import Optional

from pydantic import BaseModel, Field

from .llm import structured_completion


class AnswerCheck(BaseModel):
    """Structured verdict on answer quality and safety.

    Attributes:
        has_evidence: Retrieved chunks sufficiently support the answer.
        hallucination_risk: Answer contains content not grounded in retrieved text.
        confidence: Confidence score 0.0-1.0.
        should_refuse: Whether the answer should be withheld.
        refusal_reason: Explanation if should_refuse is True.
    """
    has_evidence: bool = Field(description="检索到的文本片段是否充分支撑该回答")
    hallucination_risk: bool = Field(description="回答中是否有模型自行编造、不基于检索内容的幻觉")
    confidence: float = Field(description="回答置信度，0.0到1.0之间")
    should_refuse: bool = Field(description="是否需要拒答（如无依据或风险过高）")
    refusal_reason: str = Field(description="拒答理由（如 should_refuse 为 true）")


_CHECK_PROMPT_TEMPLATE = """你是一个严谨的金融文档问答审核员。

请根据以下【用户问题】和【检索到的原始文本片段】以及【AI 生成的回答】，
判断该回答的质量和安全性。

原始文本片段（来自 PDF）：
{evidence}

用户问题：{query}

AI 回答：{answer}

请严格输出 JSON 格式，包含以下字段：
- has_evidence (bool): 检索到的文本片段是否充分支撑该回答
- hallucination_risk (bool): 回答中是否有模型自行编造的内容（不基于原始文本）
- confidence (float): 回答置信度，0.0到1.0
- should_refuse (bool): 是否需要拒答
- refusal_reason (str): 拒答理由（如果 should_refuse 为 true 则说明原因，否则填空字符串）

只返回 JSON，不要包含任何其他文字。"""


def check_answer(
    query: str,
    answer: str,
    evidence: list[dict],
    max_retries: int = 3,
) -> AnswerCheck:
    """Run self-check guardrail on a generated answer.

    Args:
        query: Original user question.
        answer: Answer generated by the LLM.
        evidence: Retrieved document chunks (list of dicts with "content" key).
        max_retries: Maximum self-healing retries on parse/validation failure.

    Returns:
        A validated AnswerCheck instance.

    Raises:
        RuntimeError: If after max_retries the model cannot produce valid JSON.
    """
    # Format evidence text
    evidence_text = ""
    for i, chunk in enumerate(evidence):
        page = chunk.get("page", "?")
        content = chunk.get("content", "")
        evidence_text += f"[来源 第{page}页] {content}\n\n"
    if not evidence_text:
        evidence_text = "(无检索结果)"

    prompt = _CHECK_PROMPT_TEMPLATE.format(
        evidence=evidence_text.strip(),
        query=query,
        answer=answer,
    )

    messages = [
        {"role": "system", "content": "你是一个严谨的金融文档问答审核员。请始终输出纯 JSON。"},
        {"role": "user", "content": prompt},
    ]

    last_error = None
    raw = ""  # initialize to avoid UnboundLocalError in except block
    for attempt in range(1, max_retries + 1):
        try:
            raw = structured_completion(
                system_prompt="你是一个严谨的金融文档问答审核员。请始终输出纯 JSON。",
                user_prompt=prompt,
                temperature=0.0,
            )

            # Strip markdown code fences if present
            clean = raw.replace("```json", "").replace("```", "").strip()

            parsed = json.loads(clean)
            return AnswerCheck.model_validate(parsed)

        except (json.JSONDecodeError, Exception) as e:
            last_error = str(e)
            # Append correction instruction for the next attempt
            messages.append({"role": "assistant", "content": raw})
            messages.append({
                "role": "user",
                "content": f"输出格式错误：{last_error}\n请严格按照 JSON 格式重新输出，不要包含任何额外文字。",
            })

    raise RuntimeError(
        f"Self-check guardrail failed after {max_retries} retries: {last_error}"
    )
