"""State schema for the Financial Document Q&A Agent.

Uses TypedDict(total=False) to match the pattern from
parallel-topic-analyzer/src/state.py.
"""

from typing import Any, TypedDict


class FinancialQaState(TypedDict, total=False):
    """State for the financial document QA workflow.

    Attributes:
        query: User's question about the financial document.
        intent: Classified intent — "relevant", "irrelevant", or "unanswerable".
        retrieved_chunks: Document chunks retrieved from vector search,
            each with page, content, and relevance score.
        answer: Final answer generated by the LLM.
        citations: List of source page references (e.g. ["第44页", "第90页"]).
        has_evidence: Whether retrieved chunks provide sufficient evidence.
        hallucination_risk: Whether the answer may contain fabricated content.
        should_refuse: Whether the agent should refuse to answer.
        refusal_reason: Explanation for refusal.
        errors: List of errors encountered during processing.

        # Internal runtime fields (prefixed with _)
        _retriever: Chroma vector store injected at runtime.
        _persist_dir: Chroma DB persist directory path.
    """
    query: str
    intent: str
    retrieved_chunks: list[dict]
    answer: str
    citations: list[str]
    has_evidence: bool
    hallucination_risk: bool
    should_refuse: bool
    refusal_reason: str
    errors: list[str]
    _retriever: Any  # ParentDocumentRetriever — avoid import cycle / runtime typing
    _persist_dir: str
